apiVersion: "app.redislabs.com/v1alpha1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise"
spec:
  nodes: 7
  persistentSpec:
    enabled: false
    storageClassName: "zeroedthick" # ! edit according to infrastructure
  uiServiceType: LoadBalancer
  username: "admin@acme.com"
  redisEnterpriseNodeResources:
    limits:
      cpu: "4000m"
      memory: 50Gi
    requests:
      cpu: "4000m"
      memory: 10Gi
  redisEnterpriseImageSpec:
    imagePullPolicy:  Always
    repository:       redislabs/redis
    versionTag:       5.4.0-19.no_ipv6

